[package]
name = "coreos-assembler"
version = "0.1.0"
authors = ["Colin Walters <walters@verbum.org>"]

[dependencies]
tempfile = "3.0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
